### ISSUE TITLE
How can i add dutch voice?

### ISSUE THREAD

**Issue by sven8100** [phyce/rl-natural-speech#9]
Hello, i'm wondering if there is an dutch voice that works, I found this one https://huggingface.co/rhasspy/piper-voices/tree/main/nl/nl_NL/mls/medium but i cannot make it works, can u help? Great plugin tho

**Comment by phyce** [comment]
Hello, I have initially had the dutch language model added into the plugin but ended up removing it because the quality wasn't great. I have considered re-training the model (along with more languages) myself to see if I can improve it but had no time to figure out training yet.
I'm happy to re-add it for you, unless you'd rather wait for the higher quality one.
Glad you like the plugin!

**Comment by phyce** [comment]
[I have re-added dutch](https://github.com/phyce/rl-natural-speech/commit/0400b9a179ebc70de604828d70df270e5c2dac92), expect the update to be out on runelite soon, when it gets approved by the devs.
